name: Build and Publish Fritz

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Fritz Library
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      #- name: Restore NuGet packages
      #  run: nuget restore Fritz.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Fritz project
        run: msbuild Fritz\Fritz.csproj /p:Configuration=Release

      - name: Pack NuGet package (from .csproj metadata) 
        run: nuget pack Fritz/Fritz.csproj -Properties Configuration=Release -OutputDirectory ./nupkg

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkg/*.nupkg
          retention-days: 5

  publish:
    name: Publish to NuGet.org
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg

      - name: Publish package to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

